KnowledgeBase/KnowledgeBase.Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeBase.Web.Controllers
{
    public class PostController : BaseController
    {
        // GET: Post
        public ActionResult Index()
        {
            return View();
        }

        // GET: Post/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Post/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Post/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Post/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Post/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

KnowledgeBase/KnowledgeBase.Web/Views/Post/Create.cshtml
@model KnowledgeBase.BLL.Models.Post
@using KnowledgeBase.Web.App_GlobalResources;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Ajax.BeginForm("Create", "Post", new AjaxOptions { HttpMethod = "POST", LoadingElementId = "spinner", UpdateTargetId = "add-form" }, new { id = "creationForm_instructor" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="add-form">
            <div class="row">
                <div class="col-md-4">
                    <fieldset>
                        <legend>@Post.AddingPost_CreatePost_Label</legend>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Title)
                                @Html.ValidationMessageFor(model => model.Title)
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
        </div>
    </div>
}